version: "3.2"
services:
   web:
      build: .
      ports:
         - "8000:8000"
      volumes:
         - .:/app
      depends_on:
         - redis
      environment:
         - REDIS_HOST=redis
         - REDIS_PASSWORD=sOmE_sEcUrE_pAsS
         - REDIS_PORT=6379
   redis:
      image: "redis:alpine"
      command: redis-server --requirepass sOmE_sEcUrE_pAsS
      ports:
         - "6379:6379"
      volumes:
         - $PWD/redis-data:/var/lib/redis
         - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
      environment:
         - REDIS_REPLICATION_MODE=master
